language: dart
sudo: false
dart:
  - dev

cache:
  directories:
    - $HOME/.pub-cache

# Custom test runner.
script: dart ./tool/test.dart

dart_task:
  - dartanalyzer
  - dartfmt

matrix:
  # Only run dartfmt checks with the current SDK.
  exclude:
    - dart: dev
      dart_task: dartfmt
    - dart: dev
      dart_task: dartanalyzer
